max_iterations: 50
checkpoint_interval: 5
llm:
  primary_model: Qwen3-8B
  primary_model_weight: 1
  api_base: http://127.0.0.1:8080/v1
  api_key: code-efficiency
  temperature: 0.7
  max_tokens: 16000
  timeout: 120
prompt:
  system_message: "\"You are an expert programmer specializing in advanced algorithm\
    \ design and implement, focus on correctness, time efficiency and memory efficiency.\
    \ \n\nPlease based on the task description write Solution to pass the provided\
    \ test cases. \nYou must follow the following rules:\nFirst, the code should be\
    \ in ```python\\n[Code]\\n``` block.\nSecond, You should not add the provided\
    \ test cases into your ```\\npython[Code]\\n``` block.\nThird, You are not need\
    \ to write the test cases, we will provide the test cases for you.\nFinally, You\
    \ should make sure that the provided test cases can pass your solution.\n\n\n\
    # Task description:\nYou are given two non-empty linked lists representing two\
    \ non-negative integers. The digits are stored in reverse order, and each of their\
    \ nodes contains a single digit. Add the two numbers and return the sum as a linked\
    \ list.\n\nYou may assume the two numbers do not contain any leading zero, except\
    \ the number 0 itself.\n\n \nExample 1:\n\nInput: l1 = [2,4,3], l2 = [5,6,4]\n\
    Output: [7,0,8]\nExplanation: 342 + 465 = 807.\n\n\nExample 2:\n\nInput: l1 =\
    \ [0], l2 = [0]\nOutput: [0]\n\n\nExample 3:\n\nInput: l1 = [9,9,9,9,9,9,9], l2\
    \ = [9,9,9,9]\nOutput: [8,9,9,9,0,0,0,1]\n\n\n \nConstraints:\n\n\n\tThe number\
    \ of nodes in each linked list is in the range [1, 100].\n\t0 <= Node.val <= 9\n\
    \tIt is guaranteed that the list represents a number that does not have leading\
    \ zeros.\n\n\n\n\nIMPORTANT: Do not rewrite the entire program - focus on targeted\
    \ improvements wrapped in EVOLVE-BLOCK-START and EVOLVE-BLOCK-START. And you must\
    \ use <<<<<<< SEARCH, ======= and >>>>>> REPLACE diff format to change the code.\"\
    \n"
  template_dir: /data/CodeEfficiency/openevolve/openevolve/prompts/defaults
database:
  population_size: 50
  archive_size: 20
  num_islands: 3
  elite_selection_ratio: 0.2
  exploitation_ratio: 0.7
  log_prompts: true
evaluator:
  timeout: 60
  enable_artifacts: true
  parallel_evaluations: 2
diff_based_evolution: true
max_code_length: 20000
