language: python3
time_limit: 3
memory_limit: 512
num_runs: 6
trimming_fraction: 0.1
max_workers: 9
task_data_path: "/data/CodeEfficiency/benchmark/EffiBench-X/data/dataset/aizu_1444_yokohama-phenomena.json"