# Configuration for function minimization example
max_iterations: 50
checkpoint_interval: 5

# LLM configuration
llm:
  primary_model: "google/gemini-2.5-flash-lite"
  # primary_model: "llama3.1-8b"
  primary_model_weight: 0.8
  secondary_model: "google/gemini-2.5-flash"
  # secondary_model: "llama-4-scout-17b-16e-instruct"
  secondary_model_weight: 0.2
  # 2025.9.16: Revise for openrouter.ai
  api_base: https://openrouter.ai/api/v1
  api_key: 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                     
  temperature: 0.7
  max_tokens: 16000
  timeout: 120

# Prompt configuration
prompt:
  # 2025.9.17: Shed light on some requirements
  system_message: |
    "You are an expert programmer specializing in advanced algorithm design and implement, focus on correctness, time efficiency and memory efficiency. 
    
    Please based on the task description write Solution to pass the provided test cases. 
    You must follow the following rules:
    First, the code should be in ```python\n[Code]\n``` block.
    Second, You should not add the provided test cases into your ```\npython[Code]\n``` block.
    Third, You are not need to write the test cases, we will provide the test cases for you.
    Finally, You should make sure that the provided test cases can pass your solution.


    # Task description:
    Given two sorted arrays `nums1` and `nums2` of size `m` and `n` respectively, return **the median** of the two sorted arrays.\n\n\nThe overall run time complexity should be `O(log (m+n))`.\n\n\n\u00a0\n\n\n**Example 1:**\n\n\n\n```\n\n**Input:** nums1 = [1,3], nums2 = [2]\n**Output:** 2.00000\n**Explanation:** merged array = [1,2,3] and median is 2.\n\n```\n\n**Example 2:**\n\n\n\n```\n\n**Input:** nums1 = [1,2], nums2 = [3,4]\n**Output:** 2.50000\n**Explanation:** merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.\n\n```\n\n\u00a0\n\n\n**Constraints:**\n\n\n* `nums1.length == m`\n* `nums2.length == n`\n* `0 <= m <= 1000`\n* `0 <= n <= 1000`\n* `1 <= m + n <= 2000`\n* `-106 <= nums1[i], nums2[i] <= 106`\n\n\n

    IMPORTANT: Do not rewrite the entire program - focus on targeted improvements wrapped in EVOLVE-BLOCK-START and EVOLVE-BLOCK-START. And you must use <<<<<<< SEARCH and >>>>>> REPLACE diff format to change the code."
  
  # 2025.9.17: Add Template Dir
  template_dir: "/data/CodeEfficiency/openevolve/openevolve/prompts/enhanced"

# Database configuration
database:
  population_size: 50
  archive_size: 20
  num_islands: 3
  elite_selection_ratio: 0.2
  exploitation_ratio: 0.7
  log_prompts: true # Enable logging of prompts for debugging

# Evaluator configuration
evaluator:
  timeout: 60
  cascade_thresholds: [1.3]
  parallel_evaluations: 3

# Evolution settings
diff_based_evolution: true
max_code_length: 20000